name: Deploy webstudio-site to GitHub Pages

on:
  push:
    branches:
      - webstudio-site

jobs:
  upload:
    name: Upload artifact for Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the repository root (this repo contains the static export)
          path: .

  deploy:
    name: Deploy to GitHub Pages
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1
